version: "3.3"

services:
  mysql:
    image: "$SQL_IMAGE"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $SQL_NAME
      MYSQL_USER: $SQL_USER
      MYSQL_PASSWORD: $SQL_PASS


  backend:
    image: "${DOCKER_REGISTRY}/byot/backend-main:${DOCKER_TAG}"
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "${PORT_BACKEND_MAIN}:5000"
    depends_on:
      - mysql

  frontend_web_app:
    image: "${DOCKER_REGISTRY}/byot/frontend-web-app:${DOCKER_TAG}"
    build:
      context: .
      dockerfile: frontend-web.dockerfile
      shm_size: '4g'
      args:
        BUILD_PROJECT: "web/app"
    ports:
      - "${PORT_FRONTEND_WEB_APP}:5000"
