image: node:13

cache:
  paths:
    - scripts/node_modules
    - scripts/yarn.lock
    - frontend/node_modules
    - frontend/yarn.lock
    - frontend/web/**/node_modules
    - frontend/web/**/yarn.lock

stages:
  - prebuild
  - build
  - test
  - deploy

before_script:
  - cd frontend
  - yarn install

Create favicon:
  stage: prebuild
  cache:
    paths:
      - scripts/node_modules
  artifacts:
    paths:
      - scripts/out
  before_script:
    - apt-get update
    - apt-get install -yq chromedriver libatk-bridge2.0-0 libgtk-3-0
  script:
    - cd scripts
    - yarn install
    - yarn logo:generate
    - yarn logo:favicon:generate

Build project:
  stage: build
  dependencies:
    - Create favicon
  artifacts:
    paths:
      - frontend/web/admin/build
      - frontend/web/app/build
      - frontend/web/landing/build
  script:
    - cd ../scripts
    - yarn install
    - yarn logo:favicon:inject -p admin
    - yarn logo:favicon:inject -p app
    - yarn logo:favicon:inject -p landing
    - cd ../frontend/web/common
    - cd ../admin
    - yarn build
    - cd ../app
    - yarn build
    - cd ../landing
    - yarn build

Build storybook:
  stage: build
  dependencies:
    - Create favicon
  artifacts:
    paths:
      - frontend/web/storybook/storybook-static
  before_script:
    - cd frontend/web/storybook
    - yarn install
  script:
    - yarn build-storybook

Unit tests:
  stage: test
  dependencies:
    - Build project
  artifacts:
    paths:
      - frontend/common/coverage
      - frontend/web/common/coverage
      - frontend/web/admin/coverage
      - frontend/web/app/coverage
      - frontend/web/landing/coverage
  script:
    - cd common
    - yarn test --coverage
    - cd ../web/common
    - yarn test --coverage
    - cd ../admin
    - yarn test --coverage
    - cd ../app
    - yarn test --coverage
    - cd ../landing
    - yarn test --coverage

e2e tests:
  stage: test
  dependencies:
    - Build project
  artifacts:
    paths:
      - frontend/web/test/cypress/videos
      - frontend/web/test/cypress/screenshots
  script:
    # todo remove when deployed somewhere
    - exit 0
    - cd frontend/web/test
    # - yarn test -b chrome --headless
    # run tests

Deploy:
  stage: deploy
  dependencies:
    - Build project
    - Unit tests
    - e2e tests
  script:
    - echo "Deploying"

