image: node:12

stages:
  - build
  - test
  - deploy

before_script:
  - yarn install

.build:
  stage: build
  artifacts:
    paths:
      - build
  script:
    - yarn build

.test:
  stage: test
  script:
    - yarn test

.deploy:
  script:
    - echo "Deploying"
