image: node:13

cache:
  paths:
    - scripts/node_modules
    - scripts/yarn.lock
    - frontend/node_modules
    - frontend/yarn.lock
    - frontend/web/**/node_modules
    - frontend/web/**/yarn.lock

stages:
  - prebuild
  - build
  - test
  - deploy

before_script:
  - cd frontend
  - chown -R "$USER:$GROUP" .
  - yarn install

Create favicon:
  image: alekzonder/puppeteer:latest
  stage: prebuild
  cache:
    paths:
      - scripts/node_modules
  artifacts:
    paths:
      - scripts/out
  before_script:
    - echo "before"
  script:
    - cd scripts
    - chown -R "$USER:$GROUP" .
    - yarn install
    - yarn logo:favicon:generate

Build project:
  stage: build
  dependencies:
    - Create favicon
  artifacts:
    paths:
      - frontend/web/admin/build
      - frontend/web/app/build
      - frontend/web/landing/build
  script:
    - cd ../scripts
    - chown -R "$USER:$GROUP" .
    - yarn install
    - yarn logo:favicon:inject frontend/web/admin
    - yarn logo:favicon:inject frontend/web/app
    - yarn logo:favicon:inject frontend/web/landing
    - cd ../frontend/web/common
    - cd ../admin
    - yarn build
    - cd ../app
    - yarn build
    - cd ../landing
    - yarn build

Build storybook:
  stage: build
  dependencies:
    - Create favicon
  artifacts:
    paths:
      - frontend/web/storybook/storybook-static
  before_script:
    - cd frontend/web/storybook
    - chown -R "$USER:$GROUP" .
    - yarn install
  script:
    - yarn build-storybook

Unit tests:
  stage: test
  cache:
    paths:
      - ./frontend/**/__snapshots__
  dependencies:
    - Build project
  script:
    - cd web/common
    - cd ../common
    - yarn test
    - cd ../admin
    - yarn test
    - cd ../app
    - yarn test
    - cd ../landing
    - yarn test

Regression test:
  cache:
    paths:
      - .loki
  artifacts:
    paths:
      - frontend/web/storybook/.loki/**
  image: alekzonder/puppeteer:latest
  stage: test
  dependencies:
    - Build storybook
  before_script:
    - cd frontend/web/storybook
    - chown -R "$USER:$GROUP" .
    - yarn install
  script:
    - yarn test:ci

Deploy:
  stage: deploy
  dependencies:
    - Build project
    - Unit tests
    - Regression test
  script:
    - echo "Deploying"

