image: node:12

variables:
  WEB_ROOT: "frontend/web"

cache:
  paths:
    - "$WEB_ROOT/node_modules"
    - "$PROJECT_PATH/node_modules"

stages:
  - build
  - test
  - deploy

before_script:
  - yarn install

.build:
  stage: build
  script:
    - yarn build

.test:
  stage: test
  script:
    - yarn test

.deploy:
  stage: deploy
  script:
    - echo "Deploying"
