image: node:13

variables:
  WEB_ROOT: "frontend/web"
  PROJECT_PATH: "$WEB_ROOT/$PROJECT_NAME"
  SCRIPTS_PATH: scripts

cache:
  paths:
    - "$WEB_ROOT/node_modules"
    - "$PROJECT_PATH/node_modules"
    - "$SCRIPTS_PATH/node_modules"

stages:
  - build
  - test
  - deploy

before_script:
  - cd "$PROJECT_PATH"
  - yarn install

Build:
  image: alekzonder/puppeteer:latest
  stage: build
  artifacts:
    name: "${PROJECT_NAME}-artifacts"
    paths:
      - "$PROJECT_PATH/build"
      - "$PROJECT_PATH/views/assets/generated"
  script:
    - cd ../../..
    - cd "$SCRIPTS_PATH"
    - yarn install
    - yarn logo:favicon:generate
    - yarn logo:favicon:inject "$PROJECT_PATH"
    - cd ..
    - cd "$PROJECT_PATH"
    - yarn build

Unit test project:
  stage: test
  cache:
    paths:
      - ./**/__snapshots__
  dependencies:
    - Build
  script:
    - yarn test

Unit test common:
  stage: test
  cache:
    paths:
      - ./**/__snapshots__
  dependencies:
    - Build
  script:
    - yarn test

Regression test:
  cache:
    paths:
      - .loki
  artifacts:
    paths:
      - frontend/web/storybook/.loki/**
  image: alekzonder/puppeteer:latest
  stage: test
  dependencies:
    - Build
  before_script:
    - cd frontend/web/storybook
    - yarn install
  script:
    - yarn test

Deploy:
  stage: deploy
  dependencies:
    - Build
    - Unit test project
    - Unit test common
    - Regression test
  script:
    - echo "Deploying $PROJECT_NAME"

