image: node:13

cache:
  paths:
    - scripts/node_modules
    - scripts/yarn.lock
    - frontend/node_modules
    - frontend/yarn.lock
    - frontend/web/**/node_modules
    - frontend/web/**/yarn.lock

stages:
  - prebuild
  - build
  - test
  - deploy

before_script:
  - cd frontend
  - yarn install

Create favicon:
  stage: prebuild
  cache:
    paths:
      - scripts/node_modules
  artifacts:
    paths:
      - scripts/out
  before_script:
    - apt-get update
    - apt-get install -yq chromedriver libatk-bridge2.0-0 libgtk-3-0
  script:
    - cd scripts
    - yarn install
    - yarn logo:favicon:generate

Build project:
  stage: build
  dependencies:
    - Create favicon
  artifacts:
    paths:
      - frontend/web/admin/build
      - frontend/web/app/build
      - frontend/web/landing/build
  script:
    - cd ../scripts
    - yarn install
    - yarn logo:favicon:inject frontend/web/admin
    - yarn logo:favicon:inject frontend/web/app
    - yarn logo:favicon:inject frontend/web/landing
    - cd ../frontend/web/common
    - cd ../admin
    - yarn build
    - cd ../app
    - yarn build
    - cd ../landing
    - yarn build

Build storybook:
  stage: build
  dependencies:
    - Create favicon
  artifacts:
    paths:
      - frontend/web/storybook/storybook-static
  before_script:
    - cd frontend/web/storybook
    - yarn install
  script:
    - yarn build-storybook

Unit tests:
  stage: test
  cache:
    paths:
      - ./frontend/**/__snapshots__
  dependencies:
    - Build project
  script:
    - cd web/common
    - cd ../common
    - $([[ "`find . -name __snapshots__ -prune -print | grep -v \"node_modules\" | wc -l | grep -o "[0-9]\+"`" -gt 0 ]] && yarn test:update)
    - yarn test
    - cd ../admin
    - $([[ "`find . -name __snapshots__ -prune -print | grep -v \"node_modules\" | wc -l | grep -o "[0-9]\+"`" -gt 0 ]] && yarn test:update)
    - yarn test
    - cd ../app
    - $([[ "`find . -name __snapshots__ -prune -print | grep -v \"node_modules\" | wc -l | grep -o "[0-9]\+"`" -gt 0 ]] && yarn test:update)
    - yarn test
    - cd ../landing
    - $([[ "`find . -name __snapshots__ -prune -print | grep -v \"node_modules\" | wc -l | grep -o "[0-9]\+"`" -gt 0 ]] && yarn test:update)
    - yarn test

Regression test:
  cache:
    paths:
      - .loki
  artifacts:
    when: always
    paths:
      - frontend/web/storybook/.loki/**
  stage: test
  dependencies:
    - Build storybook
  before_script:
    - apt-get update
    - apt-get install -yq chromedriver libatk-bridge2.0-0 libgtk-3-0
    - cd frontend/web/storybook
    - yarn install
  script:
    - yarn test:ci

Deploy:
  stage: deploy
  dependencies:
    - Build project
    - Unit tests
    - Regression test
  script:
    - echo "Deploying"

