image: node:12

variables:
  WEB_ROOT: "frontend/web"
  PROJECT_PATH: "$WEB_ROOT/$PROJECT_NAME"
  SCRIPTS_PATH: scripts

cache:
  paths:
    - "$WEB_ROOT/node_modules"
    - "$PROJECT_PATH/node_modules"
    - "$SCRIPTS_PATH/node_modules"

stages:
  - build
  - test
  - deploy

before_script:
  - cd "$PROJECT_PATH"
  - yarn install

Build:
  image: alekzonder/puppeteer:latest
  stage: build
  artifacts:
    name: "${PROJECT}-artifacts"
    paths:
      - "$PROJECT_PATH/build"
      - "$PROJECT_PATH/views/assets/generated"
  script:
    - cd ../../..
    - cd "$SCRIPTS_PATH"
    - yarn install
    - yarn logo:favicon:generate
    - yarn logo:favicon:inject "$PROJECT_PATH"
    - cd ..
    - cd "$PROJECT_PATH"
    - yarn build

Test:
  stage: test
  dependencies:
    - Build
  script:
    - yarn test

Deploy:
  stage: deploy
  dependencies:
    - Build
    - Test
  script:
    - echo "Deploying $PROJECT_NAME"

