image: node:12

stages:
  - build
  - test
  - deploy

before_script:
  - yarn install

.build:
  stage: build
  script:
    - yarn build

.test:
  dependencies:
    - .build
  stage: test
  script:
    - yarn test

.deploy:
  dependencies:
    - .build
    - .test
  stage: deploy
  script:
    - echo "Deploying"
