image: node:12

variables:
  WEB_ROOT: "frontend/web"
  PROJECT_PATH: "$WEB_ROOT/$PROJECT_NAME"

cache:
  paths:
    - "$WEB_ROOT/node_modules"
    - "$PROJECT_PATH/node_modules"

stages:
  - build
  - test
  - deploy

before_script:
  - cd "$PROJECT_PATH"
  - yarn install

Build:
  artifacts:
    paths:
      - "$PROJECT_PATH/build"
  stage: build
  script:
    - yarn build

Test:
  dependencies:
    - Build
  stage: test
  script:
    - yarn test

Deploy:
  dependencies:
    - Build
    - Test
  stage: deploy
  script:
    - echo "Deploying $PROJECT_NAME"
