image: node:12

cache:
  paths:
    - node_modules

before_script:
  - cd backend/main
  - yarn install

stages:
  - build
  - test
  # - deploy

Build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - backend/main/dist

Test e2e:
  stage: test
  dependencies:
    - Build
  script:
    - ./node_modules/.bin/ts-node src/migrate.ts
    - yarn test:e2e

Test unit:
  stage: test
  script:
    - yarn test
