image: node:13

variables:
  SCRIPTS_PATH: scripts
  PROJECT_PATH: backend/main

cache:
  paths:
    - "$PROJECT_PATH/node_modules"
    - "$SCRIPTS_PATH/node_modules"

before_script:
  - cd "$PROJECT_PATH"
  - yarn install

stages:
  - build
  - test
  # - deploy

Build:
  image: alekzonder/puppeteer:latest
  stage: build
  script:
    - cd ../..
    - cd "$SCRIPTS_PATH"
    - yarn install
    - yarn logo:generate:basic
    - cd ..
    - mv "$SCRIPTS_PATH"/out/raw/* "$PROJECT_PATH/views/assets/generated"
    - cd "$PROJECT_PATH"
    - yarn build
  artifacts:
    paths:
      - "$PROJECT_PATH/dist"
      - "$PROJECT_PATH/views/assets/generated"

Test e2e:
  stage: test
  dependencies:
    - Build
  script:
    - ./node_modules/.bin/ts-node src/migrate.ts
    - yarn test:e2e

Test unit:
  stage: test
  script:
    - yarn test
